sudo: false

language: node_js

node_js:
  - "10.15.1"

script:
  - npm run lint

after_success:
  - npm run test

deploy:
  provider: npm
  email: 927627286@qq.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    all_branches: true
